# Generated by Django 3.2.9 on 2021-11-28 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_persona_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('proyecto_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=600)),
                ('link_en_vivo', models.URLField()),
                ('link_en_codigo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoImagen',
            fields=[
                ('proyecto_imagen_id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.proyecto')),
            ],
        ),
    ]
