# Generated by Django 3.2.9 on 2021-11-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_proyecto_proyectoimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='link_en_codigo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='link_en_vivo',
            field=models.URLField(blank=True),
        ),
    ]
