# Generated by Django 3.2.9 on 2021-11-28 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_proyectoimagen_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoimagen',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectoImagen', to='home.proyecto'),
        ),
    ]
