# Generated by Django 3.2.9 on 2021-12-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_proyectoimagen_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(default='perfil.png', upload_to='static/upload/profile_image/'),
            preserve_default=False,
        ),
    ]
